fix: executor settings env vars
snakemake/snakemake-executor-plugin-azure-batch pull request #4
Opened 2023-11-24 23:10 UTC by jakevc

2023-12-04 17:41 UTC, johanneskoester requested changes

2023-12-04 17:41 UTC, johanneskoester commented on snakemake_executor_plugin_azure_batch/__init__.py
> +    container_image: Optional[str] = field(
container_image is a global snakemake option. The executor does not need its own: https://github.com/snakemake/snakemake/blob/aa1c2839165fc03d20e5a28657b2e1fa7ffdf80e/snakemake/settings.py#L349

2023-12-06 17:21 UTC, jakevc commented
Is it obvious to you why this is failing @johanneskoester ? I am having a hard time tracking down why this KeyError... https://github.com/snakemake/snakemake-executor-plugin-azure-batch/actions/runs/7117767600/job/19379237614#step:8:102

2023-12-07 08:32 UTC, johanneskoester commented
> Is it obvious to you why this is failing @johanneskoester ? I am having a hard time tracking down a fix.. https://github.com/snakemake/snakemake-executor-plugin-azure-batch/actions/runs/7117767600/job/19379237614#step:8:102
> 
> Seems like it's trying to update the job in postprocess after the job is done

This is suprising, the other executors don't have that problem. I have added a debug message to the main Snakemake branch, let's see whether a rerun sheds some light on this.

2023-12-07 09:55 UTC, johanneskoester approved these changes

2023-12-07 09:56 UTC, johanneskoester commented
Yay, fixed! The problem was that you reported job success and error multiple times. THose have to be called only once per job.

2023-12-07 09:56 UTC, merged

2023-12-07 17:12 UTC, jakevc commented
awesome, thanks